# Generated by Django 3.0.3 on 2020-07-24 04:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL of the site this feed refers to. Also is used as GUID.')),
                ('title', models.TextField(verbose_name='Default name of the feed.')),
                ('preferred_title', models.TextField(default=models.TextField(verbose_name='Default name of the feed.'), verbose_name='User-preferred name of the feed. By default same as title.')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description taken from feed.')),
                ('picture', models.URLField(blank=True, default='static/images/default_feed.ico', verbose_name='URL to the picture.')),
                ('update_frequency', models.PositiveIntegerField(default=600, verbose_name='Feed update frequency in seconds.')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of last update of this Feed.')),
                ('last_updated', models.DateTimeField(verbose_name='Date and time when this feed was last checked for updates')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date when this Feed was added to the database.')),
                ('is_available', models.BooleanField(default=True, verbose_name="False if last update wasn't succesful.")),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title of this folder')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(verbose_name='True if read, False(default) if not read')),
                ('title', models.TextField(verbose_name='Name of the Post')),
                ('release_date', models.DateTimeField(verbose_name='Date and time when this post was released')),
                ('recieved_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time when this post was recieved')),
                ('url', models.URLField(verbose_name='Link that this post refers to')),
                ('is_starred', models.BooleanField(verbose_name='True is starred, False(default) if not starred')),
                ('guid', models.TextField(verbose_name="Unigue GUID for this post. When checking for new posts server will compare posts' GUID.")),
                ('parent_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_backend.Feed', verbose_name='Database link to the Feed this Post came from')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser_backend.Folder', verbose_name='Database link to the Folder this Feed is put into.'),
        ),
    ]
